name: build

on:
  push:
    paths:
    - '**.cs'
    - '**.csproj'
    - '.github/workflows/build.yml'
    
  pull_request:
  
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Download NiTiS Build Tools
        run: |
          cd ..
          git clone "https://github.com/NiTiS-Dev/NiTiS-Dev.github.io.git" "NiTiS-Site"
          cd NiTiS-Site/buildtools
          echo "NBT_HOME=$(pwd)" >> $GITHUB_ENV
          echo ---------------
          echo $NBT_HOME
          echo ---------------
          
          
      - name: Build
        run: |
          echo $NBT_HOME
          cd Source/
          dotnet clean
          dotnet restore
          dotnet build -c Release -o ../.build/
          
      - name: Artifact Pack 
        uses: actions/upload-artifact@v2
        with:
          path: .build/*.dll